#! /bin/bash

TDIR=$(mktemp -d)
TESTDIR=$(dirname $0)

# ======================================================================

function on_exit
{
    rm -rf "$TDIR"
}

trap on_exit EXIT

function failed
{
    echo FAILED >&2
    exit 1
}

trap failed ERR

# ======================================================================

if [[ "${HOSTNAME}" == "jagd" || "${HOSTNAME}" == "i19" ]]; then
    export LD_LIBRARY_PATH="${ACMACSD_ROOT}/lib:${LD_LIBRARY_PATH}"
    cd "$TESTDIR"
    echo ../dist/hidb5-make "$TDIR"/hidb.json.xz ./test.acd1.xz
    ../dist/hidb5-make "$TDIR"/hidb.json.xz ./test.acd1.xz
    echo ../dist/hidb5-stat "$TDIR"/hidb.json.xz
    ../dist/hidb5-stat "$TDIR"/hidb.json.xz 2>&1 | grep -v "WARNING: no lineage for"
fi
